-- =====================================================================
-- banking-springboot-microservices - BD SQL
-- Motor: PostgreSQL 17 | Base de datos: banca
-- =====================================================================

-- ---------------------------------------------------------------------
-- Roles y schemas (con credenciales de desarrollo)
-- ---------------------------------------------------------------------
CREATE ROLE ms_clientes LOGIN PASSWORD 'ms_clientes_pwd';
CREATE ROLE ms_cuentas  LOGIN PASSWORD 'ms_cuentas_pwd';

CREATE SCHEMA clientes AUTHORIZATION ms_clientes;
CREATE SCHEMA cuentas  AUTHORIZATION ms_cuentas;

ALTER ROLE ms_clientes SET search_path = clientes;
ALTER ROLE ms_cuentas  SET search_path = cuentas;

-- =====================================================================
-- Schema clientes (clients-microservices)
-- =====================================================================
SET ROLE ms_clientes;

CREATE TABLE clientes.persona (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    genero          VARCHAR(20)  NOT NULL
                    CONSTRAINT ck_persona_genero CHECK (genero IN ('MASCULINO', 'FEMENINO', 'OTRO')),
    edad            INTEGER      NOT NULL
                    CONSTRAINT ck_persona_edad CHECK (edad BETWEEN 18 AND 120),
    identificacion  VARCHAR(10)  NOT NULL
                    CONSTRAINT uk_persona_identificacion UNIQUE,
    direccion       VARCHAR(200) NOT NULL,
    telefono        VARCHAR(10)  NOT NULL
);

CREATE TABLE clientes.cliente (
    id          BIGINT       PRIMARY KEY
                CONSTRAINT fk_cliente_persona REFERENCES clientes.persona (id),
    cliente_id  UUID         NOT NULL
                CONSTRAINT uk_cliente_cliente_id UNIQUE,
    contrasena  VARCHAR(100) NOT NULL, -- hash BCrypt, nunca texto plano
    estado      BOOLEAN      NOT NULL DEFAULT TRUE
);

RESET ROLE;

-- =====================================================================
-- Schema cuentas (accounts-microservices)
-- =====================================================================
SET ROLE ms_cuentas;

CREATE TABLE cuentas.cliente_ref (
    cliente_id      UUID         PRIMARY KEY,
    nombre          VARCHAR(100) NOT NULL,
    estado          BOOLEAN      NOT NULL,
    actualizado_en  TIMESTAMPTZ  NOT NULL
);

CREATE TABLE cuentas.cuenta (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta     VARCHAR(20)    NOT NULL
                      CONSTRAINT uk_cuenta_numero_cuenta UNIQUE,
    tipo_cuenta       VARCHAR(20)    NOT NULL
                      CONSTRAINT ck_cuenta_tipo_cuenta CHECK (tipo_cuenta IN ('AHORROS', 'CORRIENTE')),
    saldo_inicial     NUMERIC(15, 2) NOT NULL
                      CONSTRAINT ck_cuenta_saldo_inicial CHECK (saldo_inicial >= 0),
    saldo_disponible  NUMERIC(15, 2) NOT NULL
                      CONSTRAINT ck_cuenta_saldo_disponible CHECK (saldo_disponible >= 0),
    estado            BOOLEAN        NOT NULL DEFAULT TRUE,
    fecha_apertura    TIMESTAMP(6)   NOT NULL,
    cliente_id        UUID           NOT NULL
                      CONSTRAINT fk_cuenta_cliente REFERENCES cuentas.cliente_ref (cliente_id)
);

CREATE INDEX idx_cuenta_cliente_id ON cuentas.cuenta (cliente_id);

CREATE TABLE cuentas.movimiento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha            TIMESTAMP(6)   NOT NULL,
    tipo_movimiento  VARCHAR(20)    NOT NULL,
    valor            NUMERIC(15, 2) NOT NULL
                     CONSTRAINT ck_movimiento_valor CHECK (valor <> 0),
    saldo            NUMERIC(15, 2) NOT NULL
                     CONSTRAINT ck_movimiento_saldo CHECK (saldo >= 0),
    cuenta_id        BIGINT         NOT NULL
                     CONSTRAINT fk_movimiento_cuenta REFERENCES cuentas.cuenta (id),
    CONSTRAINT ck_movimiento_tipo_signo CHECK (
        (tipo_movimiento = 'DEPOSITO' AND valor > 0) OR
        (tipo_movimiento = 'RETIRO'   AND valor < 0)
    )
);

CREATE INDEX idx_movimiento_cuenta_fecha ON cuentas.movimiento (cuenta_id, fecha);

CREATE TABLE cuentas.solicitud_idempotente (
    idempotency_key  VARCHAR(64)
                     CONSTRAINT pk_solicitud_idempotente PRIMARY KEY,
    numero_cuenta    VARCHAR(20)    NOT NULL,
    valor            NUMERIC(15, 2) NOT NULL,
    movimiento_id    BIGINT
                     CONSTRAINT fk_solicitud_movimiento REFERENCES cuentas.movimiento (id) ON DELETE SET NULL,
    creado_en        TIMESTAMP(6)   NOT NULL
);

RESET ROLE;
